# Generated by Django 4.2 on 2026-03-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=300)),
                ('page_subtitle', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField()),
                ('culture', models.JSONField(default=list)),
                ('benefits', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('department', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=300)),
                ('job_type', models.CharField(choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('internship', 'Internship')], max_length=20)),
                ('experience', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('responsibilities', models.JSONField(default=list)),
                ('qualifications', models.JSONField(default=list)),
                ('skills', models.JSONField(default=list)),
                ('featured', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
