# Generated by Django 4.2 on 2026-03-24 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.CharField(max_length=20, unique=True)),
                ('personal', models.JSONField()),
                ('contact', models.JSONField()),
                ('address', models.JSONField()),
                ('family', models.JSONField()),
                ('education', models.JSONField()),
                ('preferences', models.JSONField()),
                ('additional', models.JSONField(blank=True, null=True)),
                ('documents', models.FileField(upload_to='admissions/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('verified', 'Verified'), ('admitted', 'Admitted'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('ip_address', models.GenericIPAddressField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DemoRequestSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=300)),
                ('contact_person', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('cohort_size', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('scheduled', 'Scheduled'), ('closed', 'Closed')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InternshipApplicationSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('college', models.CharField(max_length=300)),
                ('degree', models.CharField(max_length=200)),
                ('graduation_year', models.CharField(max_length=4)),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('portfolio_url', models.URLField(blank=True, null=True)),
                ('resume', models.FileField(upload_to='internships/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('reviewing', 'Reviewing'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('job_position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='careers.jobposition')),
            ],
        ),
    ]
