# Generated by Django 4.2 on 2026-03-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('founded_year', models.IntegerField()),
                ('company_overview', models.TextField()),
                ('company_mission', models.TextField()),
                ('company_vision', models.TextField()),
                ('founder_name', models.CharField(max_length=200)),
                ('founder_title', models.CharField(max_length=200)),
                ('founder_bio', models.TextField()),
                ('founder_image', models.ImageField(upload_to='founders/')),
                ('timeline', models.JSONField(default=list)),
                ('business_profile_pdf', models.FileField(blank=True, null=True, upload_to='business_profile/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=300)),
                ('hero_subtitle', models.CharField(max_length=300)),
                ('hero_description', models.TextField()),
                ('hero_cta_primary', models.JSONField(default=dict)),
                ('hero_cta_secondary', models.JSONField(default=dict)),
                ('pillars', models.JSONField(default=list)),
                ('stats', models.JSONField(default=list)),
                ('featured_projects', models.JSONField(default=list)),
                ('partners', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.JSONField(default=list)),
                ('trainings', models.JSONField(default=list)),
                ('drt_open_school', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200)),
                ('tagline', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='site_meta/')),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('whatsapp', models.CharField(max_length=20)),
                ('social', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
